### ISSUE TITLE
Auto self nomination crashed while printing information after first nomination 

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/cron-jobs#100]
Here is the log from the auto-self-nominate.

```
sdk wc http://127.0.0.1:8080
Best block number: 2523960
Current Term Id: 0
Deposit Supplement: 10,000,000
Self Nomination tx sent: f9b72fbd75d98ea9e423456bd86b24b0861e96b5c3f1d17d12a115d83176179e
Candidate info
  TypeError: Cannot read property 'deposit' of undefined
      at send (/home/ubuntu/cron-jobs/auto-self-nominate/build/index.js:150:46)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

**Comment by HoOngEe** [comment]
Here is the `TypeError` part.
![code](https://user-images.githubusercontent.com/20704471/63244894-93fb1000-c299-11e9-9743-bd3f9163b1a5.png)
There is undefined check right above but I currently don't understand why `Cannot read property 'deposit' of undefined` arose.
